/**
 * @file secrets.example.h
 * @author Generated by Gemini Notebook (for Marshall Wingerson)
 * @brief Configuration template for Wi-Fi and MQTT credentials.
 * @version 1.0
 * 
 * @note RENAME THIS FILE TO "secrets.h" AND UPDATE WITH YOUR LOCAL CREDENTIALS.
 *       Do NOT commit "secrets.h" containing real credentials to your Git repository.
 */

#ifndef SECRETS_H
#define SECRETS_H

// --- WI-FI CONFIGURATION ---
#define WIFI_SSID           "YOUR_WIFI_SSID"
#define WIFI_PASSWORD       "YOUR_WIFI_PASSWORD"

// --- MQTT BROKER CONFIGURATION ---
#define MQTT_BROKER         "192.168.0.123"  // Indoor Gateway Host IP
#define MQTT_PORT           1883
#define MQTT_USER           ""               // Leave blank if anonymous access is enabled
#define MQTT_PASS           ""               // Leave blank if anonymous access is enabled

// --- DEVICE IDENTIFICATION ---
#define MQTT_CLIENT_ID      "weather_node_01"

// --- OVER-THE-AIR (OTA) SECURITY ---
#define OTA_PORT            8266
#define OTA_PASSWORD        "admin123"       // Password for IDE / CLI network flashes

#endif // SECRETS_H
