apiVersion: 1

datasources:
  - name: influxdb_telemetry
    type: influxdb
    access: proxy
    uid: influxdb_telemetry
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: ${INFLUXDB_ORG}
      defaultBucket: ${INFLUXDB_BUCKET}
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
    isDefault: true

